package com.javalibproject.Menu.Generic;

public enum MenuName {
    // Define all the menu names here

    //LOGIN MENUS//
    MAIN_LOGIN,
    USER_LOGIN,
    ADMIN_LOGIN,
    //MAIN MENUS//
    USER_MAIN_MENU,
    ADMIN_MAIN_MENU,
    //USER MENUS//
    USER_MY_PROFILE,
    USER_BORROW_BOOK,
    USER_RETURN_BOOK,
    USER_UPDATE_PROFILE,
    USER_VIEW_PROFILE,
    //ADMIN USER MENUS//
    ADMIN_SEARCH_USERS,
    ADMIN_CREATE_USERS,
    ADMIN_EDIT_USERS,
    ADMIN_DELETE_USERS,
    ADMIN_VIEW_USERS,
    //BOOK MENUS//
    ADMIN_SEARCH_BOOKS,
    ADMIN_CREATE_BOOKS,
    ADMIN_EDIT_BOOKS,
    ADMIN_DELETE_BOOKS,
    ADMIN_VIEW_BOOKS,
    ADMIN_VIEWS_ALL_BOOKS,
    //OTHER//
    LOG_OFF



}


